Repository gooddata/gooddata-ui-sdk, pull requests merged in 2024-04, with the labels that each got.

#4828 feat: add FF for Oracle
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
Labels: publish pre-release

#4825 chore: remove bear from plugin toolings
  common/config/rush/pnpm-lock.yaml
  tools/dashboard-plugin-template/.env.secrets.template
  tools/dashboard-plugin-template/package.json
  tools/dashboard-plugin-template/scripts/refresh-md.js
  tools/dashboard-plugin-template/src/harness/backend--tiger.ts
  tools/dashboard-plugin-template/src/harness/backend.ts
  tools/dashboard-plugin-template/webpack.config.cjs
  tools/plugin-toolkit/package.json
  tools/plugin-toolkit/src/_base/backend.ts
  tools/plugin-toolkit/src/_base/credentials.ts
  tools/plugin-toolkit/src/_base/env.ts
  tools/plugin-toolkit/src/_base/inputHandling/extractors.ts
  tools/plugin-toolkit/src/_base/inputHandling/validators.ts
  tools/plugin-toolkit/src/_base/terminal/prompts.ts
  tools/plugin-toolkit/src/_base/types.ts
  tools/plugin-toolkit/src/_base/utils.ts
  tools/plugin-toolkit/src/_base/workspaceTargetConfig.ts
  tools/plugin-toolkit/src/addPluginCmd/actionConfig.ts
  tools/plugin-toolkit/src/addPluginCmd/index.ts
  tools/plugin-toolkit/src/index.ts
  tools/plugin-toolkit/src/initCmd/actionConfig.ts
  tools/plugin-toolkit/src/initCmd/index.ts
  tools/plugin-toolkit/src/initCmd/processTigerFiles.ts
  tools/plugin-toolkit/src/inspectCmds/actionConfig.ts
  tools/plugin-toolkit/src/inspectCmds/inspectCmdAction.ts
  tools/plugin-toolkit/src/linkPluginCmd/actionConfig.ts
  tools/plugin-toolkit/src/linkPluginCmd/index.ts
  tools/plugin-toolkit/src/listCmds/actionConfig.ts
  tools/plugin-toolkit/src/listCmds/listCmdAction.ts
  tools/plugin-toolkit/src/removeParamsCmd/actionConfig.ts
  tools/plugin-toolkit/src/removeParamsCmd/index.ts
  tools/plugin-toolkit/src/unlinkPluginCmd/actionConfig.ts
  tools/plugin-toolkit/src/unlinkPluginCmd/index.ts
  tools/plugin-toolkit/src/updatePluginParamsCmd/actionConfig.ts
  tools/plugin-toolkit/src/updatePluginParamsCmd/index.ts
Labels: publish pre-release

#4836 FEATURE: F1-148 column width support
  libs/sdk-ui-charts/api/sdk-ui-charts.api.md
  libs/sdk-ui-charts/src/charts/index.tsx
  libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx
  libs/sdk-ui-charts/src/charts/repeater/columnWidths.ts
  libs/sdk-ui-charts/src/charts/repeater/hooks/useResizing.ts
  libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
  libs/sdk-ui-charts/src/charts/repeater/internal/columnSizing.ts
  libs/sdk-ui-charts/src/charts/repeater/internal/privateTypes.ts
  libs/sdk-ui-charts/src/charts/repeater/publicTypes.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: publish pre-release

#4833 FEATURE: LX-184 Enable filter by dependent date filters
  common/changes/@gooddata/sdk-ui-all/nen-lx-184-dependent_date_filters_2024-04-02-12-31.json
  libs/sdk-backend-bear/src/backend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/backend/capabilities.ts
  libs/sdk-backend-tiger/src/backend/index.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useAvailableDatasetsForItems.ts
  libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/hideFilters.spec.ts
  libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/mapping-dependentFilters.spec.ts.json
  libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/mapping-hideFilters.spec.ts.json
Labels: publish pre-release

#4838 feat: repeater
  libs/sdk-ui-charts/api/sdk-ui-charts.api.md
  libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx
  libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx
  libs/sdk-ui-charts/src/charts/repeater/internal/InlineColumnChart.tsx
  libs/sdk-ui-charts/src/charts/repeater/internal/InlineLineChart.tsx
  libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
  libs/sdk-ui-charts/src/charts/repeater/internal/repeaterExecution.ts
  libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/colorFactory.ts
  libs/sdk-ui-charts/src/highcharts/index.ts
  libs/sdk-ui-charts/src/interfaces/chartConfig.ts
  libs/sdk-ui-ext/src/internal/components/configurationPanels/RepeaterConfigurationPanel.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/RepeaterDescriptor.ts
Labels: ready to review, publish pre-release

#4847 BUGFIX: F1-227, F1-242 colors, empty rows
  libs/sdk-ui-charts/src/highcharts/chartTypes/_chartColoring/measure.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: publish pre-release

#4863 fix: repeater inner charts
  libs/sdk-ui-charts/src/charts/repeater/internal/dataViewToRepeaterData.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: publish pre-release

#4865 ci: test fossa att generation
  common/config/rush/pnpm-lock.yaml
  examples/playground/package.json
  libs/api-client-tiger/package.json
  libs/sdk-backend-base/package.json
  libs/sdk-backend-mockingbird/package.json
  libs/sdk-backend-spi/package.json
  libs/sdk-backend-tiger/package.json
  libs/sdk-embedding/package.json
  libs/sdk-model/package.json
  libs/sdk-ui-charts/package.json
  libs/sdk-ui-dashboard/package.json
  libs/sdk-ui-ext/package.json
  libs/sdk-ui-filters/package.json
  libs/sdk-ui-geo/package.json
  libs/sdk-ui-kit/package.json
  libs/sdk-ui-loaders/package.json
  libs/sdk-ui-pivot/package.json
  libs/sdk-ui-tests-e2e/package.json
  libs/sdk-ui-tests/package.json
  libs/sdk-ui-theme-provider/package.json
  libs/sdk-ui-vis-commons/package.json
  libs/sdk-ui-web-components/package.json
  libs/sdk-ui/package.json
  libs/util/package.json
  skel/sdk-skel-ts/package.json
  skel/sdk-skel-tsx/package.json
  tools/app-toolkit/package.json
  tools/applink/package.json
  tools/catalog-export/package.json
  tools/dashboard-plugin-template/package.json
  tools/i18n-toolkit/package.json
  tools/mock-handling/package.json
  tools/plugin-toolkit/package.json
  tools/reference-workspace/package.json
Labels: publish pre-release

#4867 fix: sanitize header menu item links to work on CDN hosted app
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
  libs/sdk-ui-kit/src/Header/tests/__snapshots__/generateHeaderMenuItemsGroups.test.ts.snap
  libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
Labels: publish pre-release

#4872 repeater: doc and examples
  common/changes/@gooddata/sdk-interactive-examples/mkn-f1-148-v6_2024-04-09-06-48.json
  common/config/rush/pnpm-lock.yaml
  docs/content/en/latest/references/visual_components/repeater_chart.md
  examples/sdk-interactive-examples/README.md
  examples/sdk-interactive-examples/examples/example-repeater/.codesandbox/tasks.json
  examples/sdk-interactive-examples/examples/example-repeater/.codesandbox/template.json
  examples/sdk-interactive-examples/examples/example-repeater/.gitignore
  examples/sdk-interactive-examples/examples/example-repeater/LICENSE
  examples/sdk-interactive-examples/examples/example-repeater/README.md
  examples/sdk-interactive-examples/examples/example-repeater/config/rush-project.json
  examples/sdk-interactive-examples/examples/example-repeater/package.json
  examples/sdk-interactive-examples/examples/example-repeater/scripts/updateWorkspaceVersion.mjs
  examples/sdk-interactive-examples/examples/example-repeater/src/App.tsx
  examples/sdk-interactive-examples/examples/example-repeater/src/Hint.tsx
  examples/sdk-interactive-examples/examples/example-repeater/src/assets/gooddata-logo.svg
  examples/sdk-interactive-examples/examples/example-repeater/src/assets/topology-bg.svg
  examples/sdk-interactive-examples/examples/example-repeater/src/backend.ts
  examples/sdk-interactive-examples/examples/example-repeater/src/catalog.ts
  examples/sdk-interactive-examples/examples/example-repeater/src/example/Example.tsx
  examples/sdk-interactive-examples/examples/example-repeater/src/index.css
  examples/sdk-interactive-examples/examples/example-repeater/src/index.tsx
  examples/sdk-interactive-examples/examples/example-repeater/src/public/favicon.ico
  examples/sdk-interactive-examples/examples/example-repeater/src/public/index.html
  examples/sdk-interactive-examples/examples/example-repeater/src/typings.d.ts
  examples/sdk-interactive-examples/examples/example-repeater/tsconfig.json
  examples/sdk-interactive-examples/examples/example-repeater/vite.config.js
  rush.json
Labels: ready to review

#4877 TRIVIAL: update localisations
  libs/sdk-ui-ext/src/internal/translations/de-DE.json
  libs/sdk-ui-ext/src/internal/translations/es-ES.json
  libs/sdk-ui-ext/src/internal/translations/fr-FR.json
  libs/sdk-ui-ext/src/internal/translations/it-IT.json
  libs/sdk-ui-ext/src/internal/translations/ja-JP.json
  libs/sdk-ui-ext/src/internal/translations/nl-NL.json
  libs/sdk-ui-ext/src/internal/translations/pt-BR.json
  libs/sdk-ui-ext/src/internal/translations/pt-PT.json
  libs/sdk-ui-ext/src/internal/translations/zh-Hans.json
Labels: publish pre-release

#4887 BUGFIX: F1-206 can't overwrite new config of Repeater
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: publish pre-release

#4890 fix catalog-export and add doc
  docs/content/en/latest/Quick_start.md
  docs/content/en/latest/references/dashboard_component/dashboard_plugins_upgrade.md
  tools/catalog-export/src/index.ts
Labels: publish pre-release

#4906 fix: repeater execution config
  libs/sdk-ui-charts/src/charts/repeater/internal/repeaterExecution.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: publish pre-release

#4913 fix: show repeater column titles for measures
  libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Labels: ready to review, publish pre-release

#4921 BUGFIX: remove ExperimentalFeatures entitlement name
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/entitlements/index.ts
Labels: publish pre-release

#4922 feat: add the stagingUpload tiger specific function
  libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
  libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
Labels: publish pre-release

#4919 feat: new SPI to replace direct API client usage in modeler and meditor
  libs/sdk-backend-base/src/customBackend/workspace.ts
  libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/index.ts
  libs/sdk-backend-spi/src/workspace/dataFilter/index.ts
  libs/sdk-backend-spi/src/workspace/index.ts
  libs/sdk-backend-spi/src/workspace/ldm/model.ts
  libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/ldm/index.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/dataFilter/index.ts
  libs/sdk-model/src/index.ts
Labels: publish pre-release

#4926 fix: re-export UploadFileResponse from sdk-backend-tiger
  libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
  libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
  libs/sdk-backend-tiger/src/index.ts
Labels: publish pre-release

#4928 FEATURE: add updateDescriptor methods to ws and org
  libs/sdk-backend-base/src/customBackend/workspace.ts
  libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts
  libs/sdk-backend-base/src/decoratedBackend/organization.ts
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/index.ts
  libs/sdk-backend-spi/src/organization/index.ts
  libs/sdk-backend-spi/src/workspace/index.ts
  libs/sdk-backend-tiger/src/backend/organization/index.ts
  libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
  libs/sdk-backend-tiger/src/backend/workspace/index.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/WorkspaceConverter.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/organization/index.ts
Labels: publish pre-release

#4933 fix: reexport result type
  libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
  libs/sdk-backend-tiger/src/index.ts
Labels: publish pre-release

#4934 fix: use quotes for search string
  libs/sdk-backend-tiger/src/backend/workspaces/index.ts
Labels: publish pre-release

#4923 FEATURE: add OpenAI config org setting
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/organization/settings/index.ts
  libs/sdk-backend-tiger/src/backend/organization/settings.ts
  libs/sdk-backend-tiger/src/backend/settings/mapping.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/settings/index.ts
Labels: publish pre-release

#4938 BUGFIX: LX-79 Adjust embedded date filter height to screen viewport
  libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
  libs/sdk-ui-filters/api/sdk-ui-filters.api.md
  libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
  libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
  libs/sdk-ui-filters/src/DateFilter/DateFilterBody/tests/DateFilterBody.test.tsx
  libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
  libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss
Labels: publish pre-release

#4948 BUGFIX: sort workspaces by name in WorkspacesQuery
  libs/sdk-backend-tiger/src/backend/workspaces/index.ts
Labels: publish pre-release

#4949 FEATURE: make children count optional in workspaces query
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/index.ts
  libs/sdk-backend-spi/src/workspace/index.ts
  libs/sdk-backend-tiger/src/backend/workspaces/index.ts
Labels: publish pre-release

#4950 TRIVIAL: Update localisations
  libs/sdk-ui-ext/src/internal/translations/de-DE.json
  libs/sdk-ui-ext/src/internal/translations/es-ES.json
  libs/sdk-ui-ext/src/internal/translations/fr-FR.json
  libs/sdk-ui-ext/src/internal/translations/it-IT.json
  libs/sdk-ui-ext/src/internal/translations/ja-JP.json
  libs/sdk-ui-ext/src/internal/translations/nl-NL.json
  libs/sdk-ui-ext/src/internal/translations/pt-BR.json
  libs/sdk-ui-ext/src/internal/translations/pt-PT.json
  libs/sdk-ui-ext/src/internal/translations/zh-Hans.json
Labels: publish pre-release

#4954 fix: reexport result type
  libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
  libs/sdk-backend-tiger/src/index.ts
Labels: publish pre-release

#4953 feat: LX-215, LX-183 feature flags for attribute filter fixes
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/settings/index.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-filters/src/AttributeFilter/types.ts
  libs/sdk-ui-filters/src/AttributeFilterHandler/types/elementsLoader.ts
Labels: publish pre-release

#4947 feat(sdk-ui-kit): add new components
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Button/Button.tsx
  libs/sdk-ui-kit/src/Button/typings.ts
  libs/sdk-ui-kit/src/Dropdown/DropdownInvertableSelect.tsx
  libs/sdk-ui-kit/src/Dropdown/index.ts
  libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
  libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelect.tsx
  libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectSearchBar.tsx
  libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectSelectionStatus.tsx
  libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectStatusBar.tsx
  libs/sdk-ui-kit/src/List/InvertableSelect/index.ts
  libs/sdk-ui-kit/src/List/InvertableSelect/useInvertableSelect.ts
  libs/sdk-ui-kit/src/List/index.ts
  libs/sdk-ui-kit/src/SeparatorLine/SeparatorLine.tsx
  libs/sdk-ui-kit/src/SeparatorLine/index.ts
  libs/sdk-ui-kit/src/index.ts
  libs/sdk-ui-kit/styles/scss/button.scss
  libs/sdk-ui-kit/styles/scss/invertableSelect.scss
  libs/sdk-ui-kit/styles/scss/main.scss
  libs/sdk-ui-kit/styles/scss/separatorLine.scss
  libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_all_elements_selected_in_negative_selection_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_empty_default_selection_-_localized_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_empty_default_selection_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_pre-selected_elements_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_single_selection_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilterButton_-_themed_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_all_elements_selected_in_negative_selection_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_empty_default_selection_-_localized_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_empty_default_selection_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_pre-selected_elements_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_single_selection_filter_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_single_selection_filter_-_themed_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_themed_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_title_with_pre-selected_elements_-_negative_AttributeFilter_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_AttributeFilter_-_title_with_pre-selected_elements_-_positive_AttributeFilter_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_DropdownActionsComponent_-_Custom_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_DropdownButtonComponent_-_Custom_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_ElementsSelectActionsComponent_-_Custom_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_ElementsSelectActionsComponent_-_Empty_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_ElementsSelectItemComponent_-_Custom_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_10_Filtersnext_Customization_StatusBarComponent_-_Custom_component_-_opened_0_document_0_desktop.png
  libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterCustomizations/StatusBarComponent.tsx
Labels: ready to review, publish pre-release
