Repository gooddata/gooddata-ui-sdk, pull requests merged in 2024-08, with the labels that each got.

#5191 feat: store widget and dashboard identifiers in visualization automation
  libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/exportDefinitions/index.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
Labels: publish pre-release

#5192 widget automation edit mode and list icon
  libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
Labels: publish pre-release

#5193 feat: drill intersection filtering configuration
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/dashboard/drill.ts
  libs/sdk-model/src/settings/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/intersectionUtils.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToInsightHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/presentation/drill/types.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributes.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributesSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/drillConfigMapper.ts
  libs/sdk-ui-dashboard/styles/scss/drillConfigPanel.scss
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectItem.tsx
  libs/sdk-ui-kit/src/List/InvertableSelect/index.ts
  libs/sdk-ui-kit/src/List/index.ts
Labels: ready to review, publish pre-release

#5195 feat: scatter plot clustering docs
  docs/content/en/latest/references/visual_components/scatter_plot.md
Labels: ready to review

#5194 fix: drill intersection filtering configuration
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributes.tsx
Labels: ready to review, publish pre-release

#5197 fix: remove column rollup totals as well
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx
Labels: publish pre-release

#5198 feat: scatter plot clustering docs
  docs/content/en/latest/references/visual_components/scatter_plot.md
Labels: ready to review

#5199 feat: disable schedule if no local identifier on widget
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.ts
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
Labels: publish pre-release

#5200 feat: store widget filters in export definition
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
Labels: publish pre-release

#5202 feat: alerting feature flags and base in sdk-model
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/automations/index.ts
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/settings/index.ts
Labels: ready to review, publish pre-release

#5203 feat: send organization tier to feature hub
  libs/api-client-tiger/api/api-client-tiger.api.md
  libs/api-client-tiger/src/profile.ts
  libs/sdk-backend-tiger/src/backend/features/hub.ts
  libs/sdk-backend-tiger/src/backend/features/index.ts
  libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
  libs/sdk-backend-tiger/src/backend/user/settings.ts
  libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Labels: publish pre-release

#5205 Revert "feat: send organization tier to feature hub"
  libs/api-client-tiger/api/api-client-tiger.api.md
  libs/api-client-tiger/src/profile.ts
  libs/sdk-backend-tiger/src/backend/features/hub.ts
  libs/sdk-backend-tiger/src/backend/features/index.ts
  libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
  libs/sdk-backend-tiger/src/backend/user/settings.ts
  libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Labels: publish pre-release

#5208 RELATED: CQ-582 Semantic Search Iteration 3
  libs/api-client-tiger/api/api-client-tiger.api.md
  libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
  libs/api-client-tiger/src/index.ts
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/genAI/index.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/genAI/index.ts
  libs/sdk-model/src/index.ts
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useAdminInformationMessage.ts
  libs/sdk-ui-kit/src/Icon/Icon.tsx
  libs/sdk-ui-kit/src/Icon/icons/HistoryBack.tsx
  libs/sdk-ui-kit/src/List/InsightListItem.tsx
  libs/sdk-ui-kit/src/List/InsightListItemDate.tsx
  libs/sdk-ui-kit/src/List/index.ts
  libs/sdk-ui-kit/src/List/tests/InsightListItemDate.test.ts
  libs/sdk-ui-kit/src/index.ts
  libs/sdk-ui-kit/src/utils/dateTimeConfig.ts
  libs/sdk-ui-kit/src/utils/debounce.ts
  libs/sdk-ui-kit/src/utils/tests/dateTimeConfig.test.ts
  libs/sdk-ui-semantic-search/api/sdk-ui-semantic-search.api.md
  libs/sdk-ui-semantic-search/src/ResultsItem.tsx
  libs/sdk-ui-semantic-search/src/SearchResultsDropdownList.tsx
  libs/sdk-ui-semantic-search/src/SemanticSearch.tsx
  libs/sdk-ui-semantic-search/src/hooks/tests/__snapshots__/useSemanticSearch.test.ts.snap
  libs/sdk-ui-semantic-search/src/hooks/tests/useResultsSelector.test.ts
  libs/sdk-ui-semantic-search/src/hooks/tests/useSemanticSearch.test.ts
  libs/sdk-ui-semantic-search/src/hooks/useListSelector.ts
  libs/sdk-ui-semantic-search/src/hooks/useSemanticSearch.ts
  libs/sdk-ui-semantic-search/src/internal/AnnotatedResultsItem.tsx
  libs/sdk-ui-semantic-search/src/internal/HeaderSearchButton.tsx
  libs/sdk-ui-semantic-search/src/internal/HistoryItem.tsx
  libs/sdk-ui-semantic-search/src/internal/SearchList.tsx
  libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
  libs/sdk-ui-semantic-search/src/internal/SearchResultsList.tsx
  libs/sdk-ui-semantic-search/src/internal/UpdateDate.tsx
  libs/sdk-ui-semantic-search/src/types.ts
  libs/sdk-ui-semantic-search/src/utils/renderDetails.tsx
  libs/sdk-ui-semantic-search/src/utils/renderItemIcon.tsx
  libs/sdk-ui-semantic-search/styles/scss/main.scss
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_full-featured_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_short_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_themed_0_document_0_desktop.png
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/index.tsx
  libs/sdk-ui/src/base/localization/bundles/en-US.json
  libs/sdk-ui/src/base/react/tests/useLocalStorage.test.ts
  libs/sdk-ui/src/base/react/useLocalStorage.ts
Labels: publish pre-release

#5210 fix: do not allow date filters without dataset to be stored in exportDef
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts
Labels: publish pre-release

#5207 feat: introduce dashboard saved filter views
  common/changes/@gooddata/sdk-ui-all/pdo-filter-views_2024-08-06-11-42.json
  examples/playground/webpack.config.cjs
  libs/api-client-tiger/api/api-client-tiger.api.md
  libs/api-client-tiger/src/gd-tiger-model/AnalyticalDashboardModelV2.ts
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/decoratedBackend/dashboards.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/dashboards/index.ts
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
  libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/dashboard/dashboard.ts
  libs/sdk-model/src/dashboard/filterContext.ts
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/settings/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/_staging/sharedHooks/useEventToastMessage.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadFilterViews.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/index.ts
  libs/sdk-ui-dashboard/src/model/commands/base.ts
  libs/sdk-ui-dashboard/src/model/commands/filters.ts
  libs/sdk-ui-dashboard/src/model/commands/index.ts
  libs/sdk-ui-dashboard/src/model/events/base.ts
  libs/sdk-ui-dashboard/src/model/events/filters.ts
  libs/sdk-ui-dashboard/src/model/events/index.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts
  libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsReducers.ts
  libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsReducersSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsState.ts
  libs/sdk-ui-dashboard/src/model/store/filterViews/index.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/model/store/meta/metaReducers.ts
  libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/meta/metaState.ts
  libs/sdk-ui-dashboard/src/model/store/types.ts
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/FiltersConfigurationPanel.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/AddFilterView.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViewDeleteConfirm.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViewsList.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/useFilterViewsToastMessages.tsx
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
  libs/sdk-ui-dashboard/styles/scss/filterBar.scss
  libs/sdk-ui-ext/src/dataLoaders/test/dataLoaders.mock.ts
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Dropdown/DropdownButton.tsx
  libs/sdk-ui-kit/src/Messages/index.ts
  libs/sdk-ui-kit/src/Messages/useToastMessage.ts
  libs/sdk-ui-kit/styles/scss/variables.scss
Labels: publish pre-release

#5214 feat: enable drill filtering by default
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
Labels: ready to review, publish pre-release

#5213 scheduling fixes for dashboard relationship and filters
  libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
Labels: publish pre-release

#5219 fix: use proper FF selector
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
Labels: publish pre-release

#5225 fix: repeat by cron expression is changed to Daily if Minute and Seco…
  libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts
  libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
Labels: publish pre-release

#5227 fix: sanitize export definition filter ids in converters
  libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
Labels: publish pre-release

#5228 feat: send organization tier to feature hub
  libs/api-client-tiger/api/api-client-tiger.api.md
  libs/api-client-tiger/src/profile.ts
  libs/sdk-backend-tiger/src/backend/features/hub.ts
  libs/sdk-backend-tiger/src/backend/features/index.ts
  libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
  libs/sdk-backend-tiger/src/backend/user/settings.ts
  libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Labels: publish pre-release

#5230 feat: enable widget identifiers by default
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
Labels: publish pre-release

#5234 fix: handle ignored filters when DF changed
  libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts
Labels: publish pre-release

#5237 feat: alerting configuration panel
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/automations/index.ts
  libs/sdk-model/src/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertActionsDropdown.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonOperatorSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertMeasureSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertTriggerModeSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlertConfiguration.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/constants.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useEditAlert.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightSubmenuContainer.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightSubmenuHeader.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/index.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
  libs/sdk-ui-dashboard/styles/scss/alerting.scss
  libs/sdk-ui-dashboard/styles/scss/main.scss
  libs/sdk-ui-kit/src/Icon/Icon.tsx
  libs/sdk-ui-kit/src/Icon/icons/Alert.tsx
  libs/sdk-ui-kit/src/Icon/icons/AlertPaused.tsx
  libs/sdk-ui-kit/src/Icon/icons/Ellipsis.tsx
  libs/sdk-ui-kit/src/List/ListItem.tsx
  libs/sdk-ui-kit/styles/icons/changes-by.svg
  libs/sdk-ui-kit/styles/icons/decreases-by.svg
  libs/sdk-ui-kit/styles/icons/increases-by.svg
  libs/sdk-ui-kit/styles/scss/SVGicons.scss
Labels: ready to review

#5241 fix: setting for default alert
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeDescription.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/locales.ts
  libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts
  libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
  libs/sdk-ui-kit/styles/scss/recurrenceForm.scss
  libs/sdk-ui/src/base/localization/bundles/en-US.json
Labels: publish pre-release

#5242 Alerting enhancements
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/presentation/constants/index.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertActionsDropdown.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonOperatorSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDeleteDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertMeasureSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertTriggerModeSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlertConfiguration.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/constants.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/messages.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useEditAlert.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuItemButton.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
  libs/sdk-ui-dashboard/styles/scss/alerting.scss
Labels: publish pre-release

#5243 feat: make saved filter views UI mobile friendly
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/assets/filter.svg
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
  libs/sdk-ui-dashboard/styles/scss/icons.scss
  libs/sdk-ui-filters/src/DateFilter/Select/Select.tsx
  libs/sdk-ui-filters/src/DateFilter/Select/SelectButton.tsx
  libs/sdk-ui-filters/src/RankingFilter/RankingFilter.tsx
  libs/sdk-ui-filters/src/RankingFilter/RankingFilterDropdown.tsx
  libs/sdk-ui-filters/src/RankingFilter/RankingFilterDropdownBody.tsx
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/CustomizableCheckmark/CustomizableCheckmark.tsx
  libs/sdk-ui-kit/src/Dialog/ExportDialog.tsx
  libs/sdk-ui-kit/src/List/MenuList.tsx
  libs/sdk-ui-kit/src/Menu/Menu.tsx
Labels: publish pre-release

#5244 FEATURE: LX-415 Add new languages date format granularities
  libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts
  libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
  libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts
  libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
Labels: publish pre-release

#5246 feat: alerting copywrite and entitlement logic
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
  libs/sdk-ui-dashboard/styles/scss/alerting.scss
Labels: publish pre-release

#5248 fix: make icon margin in dashboard config panel consistent in SDK/KD
  libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
Labels: publish pre-release

#5247 feat: intersection filtering in drill down
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-backend-tiger/src/convertors/shared/layoutConverter.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/dashboard/baseWidget.ts
  libs/sdk-model/src/dashboard/drill.ts
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/settings/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillDownHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/addDrillDownForInsightWidgetHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/drillDown.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillDownForInsightWidgetHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/removeDrillDownForInsightWidgetHandler.ts
  libs/sdk-ui-dashboard/src/model/commands/insight.ts
  libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts
  libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
  libs/sdk-ui-dashboard/src/presentation/drill/types.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/drillConfigMapper.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/tests/__snapshots__/drillConfigMapper.test.ts.snap
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/tests/drillConfigMapper.test.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts
  libs/sdk-ui-dashboard/src/types.ts
Labels: ready to review, publish pre-release

#5249 feat: rework of notification channels factory
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/tests/index.test.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/organization/notificationChannels/index.ts
  libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts
  libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts
  libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/notificationChannels/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
Labels: publish pre-release

#5251 BUGFIX: LX-453 wrong icu format localised texts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Yue.json
  libs/sdk-ui-ext/src/internal/translations/zh-Hant.json
  libs/sdk-ui/src/base/localization/bundles/zh-Hant.json
  libs/sdk-ui/src/base/localization/bundles/zh-Yue.json
Labels: do not merge

#5252 feat: include widget filters in alert definition
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/messages.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
Labels: publish pre-release

#5256 BUGFIX: LX-454 use valid IETF BCP 47 zh-HK code
  libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
  libs/sdk-ui-dashboard/src/presentation/localization/translations.ts
  libs/sdk-ui-ext/src/internal/translations/zh-HK.json
  libs/sdk-ui-ext/src/internal/utils/translations.ts
  libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
  libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts
  libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/localization/Locale.ts
  libs/sdk-ui/src/base/localization/bundles/zh-HK.json
  libs/sdk-ui/src/base/localization/messagesMap.ts
  libs/sdk-ui/src/base/localization/test/IntlStore.test.ts
  libs/util/src/tests/translationUtils.test.ts
  libs/util/src/translationUtils.ts
Labels: publish pre-release

#5258 fix: scheduling styling
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
  libs/sdk-ui-kit/styles/scss/dialogList.scss
Labels: publish pre-release

#5254 BUGFIX: LX-453 Update wrong localised icu texts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-AU.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json
  libs/sdk-ui-ext/src/internal/translations/fi-FI.json
  libs/sdk-ui-ext/src/internal/translations/zh-Hant.json
  libs/sdk-ui/src/base/localization/bundles/fi-FI.json
  libs/sdk-ui/src/base/localization/bundles/zh-HK.json
  libs/sdk-ui/src/base/localization/bundles/zh-Hant.json
Labels: publish pre-release

#5261 Add feature flag for workspace settings, introduce workspace localization SPI
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/cachingBackend/index.ts
  libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/settings/index.ts
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/settings/index.ts
  libs/sdk-ui-ext/src/dataLoaders/test/UserWorkspaceSettingsDataLoader.test.ts
Labels: publish pre-release

#5264 feat: implementation of management alerts
  libs/sdk-ui-dashboard/.dependency-cruiser.cjs
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/assets/ellipsis-hover.svg
  libs/sdk-ui-dashboard/src/assets/ellipsis.svg
  libs/sdk-ui-dashboard/src/locales.ts
  libs/sdk-ui-dashboard/src/model/react/index.ts
  libs/sdk-ui-dashboard/src/model/react/useDashboardAlerts.ts
  libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/AlertingDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/AlertingManagementDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/index.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/operator.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/utils/responsive.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/DefaultAlertingManagementDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/AlertDropdown.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/AlertsList.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/DeleteAlertConfirmDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/PauseAlertRunner.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/index.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/index.ts
  libs/sdk-ui-dashboard/src/presentation/alerting/types.ts
  libs/sdk-ui-dashboard/src/presentation/constants/zIndex.ts
  libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/AlertingDialogProvider.tsx
  libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
  libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
  libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
  libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx
  libs/sdk-ui-dashboard/src/presentation/index.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useUpdateAlert.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/index.ts
  libs/sdk-ui-dashboard/src/types.ts
  libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Dialog/Dialog.tsx
  libs/sdk-ui-kit/src/Dialog/typings.ts
Labels: publish pre-release

#5276 fix: convert displayAsLabel from IdentifierRef to idRef
  libs/sdk-embedding/src/internal/filterConvertors.ts
Labels: publish pre-release

#5278 Introduce new workspace theme and color palette settings SPI
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/cachingBackend/index.ts
  libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/settings/index.ts
  libs/sdk-backend-spi/src/workspace/styling/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/SettingWidget/StylingSettingWidget/StylingSettingBody.tsx
  libs/sdk-ui-kit/src/SettingWidget/StylingSettingWidget/StylingSettingWidget.tsx
Labels: publish pre-release

#5279 feat: introduce FF for insight changed post event event change
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
Labels: publish pre-release

#5280 feat: icon for email
  libs/sdk-ui-kit/src/Icon/Icon.tsx
  libs/sdk-ui-kit/src/Icon/icons/Email.tsx
Labels: publish pre-release

#5281 TRIVIAL: Update localisations
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-AU.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-GB.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-419.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-CA.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/it-IT.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json
  libs/sdk-ui/src/base/localization/bundles/de-DE.json
  libs/sdk-ui/src/base/localization/bundles/en-AU.json
  libs/sdk-ui/src/base/localization/bundles/en-GB.json
  libs/sdk-ui/src/base/localization/bundles/es-419.json
  libs/sdk-ui/src/base/localization/bundles/es-ES.json
  libs/sdk-ui/src/base/localization/bundles/fi-FI.json
  libs/sdk-ui/src/base/localization/bundles/fr-CA.json
  libs/sdk-ui/src/base/localization/bundles/fr-FR.json
  libs/sdk-ui/src/base/localization/bundles/it-IT.json
  libs/sdk-ui/src/base/localization/bundles/ja-JP.json
  libs/sdk-ui/src/base/localization/bundles/nl-NL.json
  libs/sdk-ui/src/base/localization/bundles/pt-BR.json
  libs/sdk-ui/src/base/localization/bundles/pt-PT.json
  libs/sdk-ui/src/base/localization/bundles/zh-HK.json
  libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
  libs/sdk-ui/src/base/localization/bundles/zh-Hant.json
Labels: publish pre-release

#5284 fix: widget ignored filters with displayAsLabel
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/decoratedBackend/dashboards.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/dashboards/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/dashboards/widgetFilters.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/layout/validation/itemValidation.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetFilterSettingsHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeKpiWidgetFilterSettingsHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/filterValidation.ts
  libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetBrokenAlerts.ts
  libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
  libs/sdk-ui-dashboard/src/model/utils/alertsUtils.ts
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts
  libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfigurationItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/FilterConfiguration.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/filterUtils.ts
Labels: publish pre-release

#5285 feat: support for default smtp
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts
  libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts
  libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/index.ts
  libs/sdk-model/src/notificationChannels/index.ts
Labels: publish pre-release

#5286 fix: wrong translation
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
Labels: publish pre-release

#5287 feat: support setting alerts for more types of vis
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
Labels: publish pre-release

#5283 feat(spi): introduce workspace SPI for clearing of theme and palette
  libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/styling/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/dataFilter/index.ts
Labels: publish pre-release

#5290 fix: handle selection over limit
  libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts
Labels: publish pre-release

#5292 fix: refresh automations on alert pause and resume
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
Labels: publish pre-release

#5293 RELATED: CQ-582 Semantic search telemetry and fixes
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/Header/Header.tsx
  libs/sdk-ui-kit/src/Header/HeaderSearchButton.tsx
  libs/sdk-ui-kit/src/Header/typings.ts
  libs/sdk-ui-kit/styles/scss/header.scss
  libs/sdk-ui-semantic-search/src/ResultsItem.tsx
  libs/sdk-ui-semantic-search/src/SearchListItem.tsx
  libs/sdk-ui-semantic-search/src/SemanticSearch.tsx
  libs/sdk-ui-semantic-search/src/hooks/tests/useSearchMetrics.test.ts
  libs/sdk-ui-semantic-search/src/hooks/useSearchMetrics.ts
  libs/sdk-ui-semantic-search/src/internal.ts
  libs/sdk-ui-semantic-search/src/internal/AnnotatedResultsItem.tsx
  libs/sdk-ui-semantic-search/src/internal/HeaderMobileSearch.tsx
  libs/sdk-ui-semantic-search/src/internal/HeaderSearchButton.tsx
  libs/sdk-ui-semantic-search/src/internal/HistoryItem.tsx
  libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
  libs/sdk-ui-semantic-search/src/utils/renderItemIcon.tsx
  libs/sdk-ui-semantic-search/src/utils/renderLock.tsx
  libs/sdk-ui-semantic-search/styles/scss/internal.scss
  libs/sdk-ui-semantic-search/styles/scss/main.scss
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_full-featured_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_internal_SearchOverlay_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_internal_SearchOverlay_themed_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_mobile_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_mobile_themed_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_short_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_14_GenAI_SemanticSearch_-_themed_0_document_0_desktop.png
  libs/sdk-ui-tests/stories/visual-regression/kit/Header/Header.tsx
  libs/sdk-ui-tests/stories/visual-regression/semanticSearch/SemanticSearch.tsx
Labels: publish pre-release

#5295 fix: update alert description based on language settings
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
Labels: publish pre-release

#5296 fix: remove all time date filter from alert filters
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
Labels: publish pre-release

#5297 feat: repair of destination select
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
Labels: publish pre-release

#5298 Alerting and scheduling extensions
  libs/sdk-ui-dashboard/src/presentation/deleteDialog/DefaultDeleteDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/deleteDialog/types.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
  libs/sdk-ui-dashboard/styles/scss/deleteDialog.scss
  libs/sdk-ui-dashboard/styles/scss/main.scss
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
  libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
  libs/sdk-ui-kit/src/utils/constants.ts
  libs/sdk-ui-kit/styles/scss/recurrenceForm.scss
  libs/sdk-ui-tests/backstop/reference/storybook_12_UI_Kit_RecurrenceForm_-_full-featured_-_default_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_12_UI_Kit_RecurrenceForm_-_full-featured_-_openedRecurrenceType_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_12_UI_Kit_RecurrenceForm_-_themed_-_default_0_document_0_desktop.png
  libs/sdk-ui-tests/backstop/reference/storybook_12_UI_Kit_RecurrenceForm_-_themed_-_openedRecurrenceType_0_document_0_desktop.png
  libs/sdk-ui/src/base/localization/bundles/en-US.json
Labels: publish pre-release

#5300 fix: cron frequency validation
  libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
Labels: publish pre-release
