Repository gooddata/gooddata-ui-sdk, pull requests merged in 2025-06, with the labels that each got.

#6533 fix: wrong assertion in export pdf test when upgrading highchart
  libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json
Labels: skip publish

#6548 feat: export dashboard to presentation commands
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/index.ts
  libs/sdk-backend-spi/src/workspace/dashboards/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPdfPresentationHandler.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPptPresentationHandler.ts
  libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
  libs/sdk-ui-dashboard/src/model/commands/index.ts
Labels: ready to review

#6585 test: correct export content
  libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json
Labels: skip publish

#6619 feat: move backstop daily tests to earlier time
  .github/workflows/test-backstop.yml
Labels: skip publish

#6655 feat: Rewrite UiFocusTrap into UiFocusManager
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/DefaultAlertingManagementDialogNew.tsx
  libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
  libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/AddFilterView.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViewsList.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx
  libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx
  libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/NotificationsPanel.tsx
  libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterVirtualisedElementsSelect.tsx
  libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterHeader.tsx
  libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
  libs/sdk-ui-kit/api/sdk-ui-kit.api.md
  libs/sdk-ui-kit/src/@ui/UiFocusManager/UiAutofocus.tsx
  libs/sdk-ui-kit/src/@ui/UiFocusManager/UiFocusManager.tsx
  libs/sdk-ui-kit/src/@ui/UiFocusManager/UiFocusTrap.tsx
  libs/sdk-ui-kit/src/@ui/UiFocusManager/UiReturnFocusOnUnmount.tsx
  libs/sdk-ui-kit/src/@ui/UiFocusManager/UiTabOutHandler.tsx
  libs/sdk-ui-kit/src/@ui/UiFocusManager/types.ts
  libs/sdk-ui-kit/src/@ui/UiFocusManager/utils.ts
  libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx
  libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.tsx
  libs/sdk-ui-kit/src/Bubble/Bubble.tsx
  libs/sdk-ui-kit/src/Dialog/DialogBase.tsx
  libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx
  libs/sdk-ui-kit/src/Header/HeaderAccount.tsx
  libs/sdk-ui-kit/src/Header/HeaderHelp.tsx
  libs/sdk-ui-kit/src/Header/HeaderSearchButton.tsx
  libs/sdk-ui-kit/src/index.ts
  libs/sdk-ui-kit/styles/scss/overlay.scss
  libs/sdk-ui-vis-commons/src/legend/PopUpLegend/LegendDialog.tsx
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/react/useCombineRefs.ts
Labels: do not merge

#6673 test: move sdk checklist to team qa channel
  .github/workflows/checklist-integrated-staging.yaml
Labels: skip publish

#6684 chore: update testing libs
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  libs/sdk-ui-charts/package.json
  libs/sdk-ui-dashboard/package.json
  libs/sdk-ui-ext/package.json
  libs/sdk-ui-filters/package.json
  libs/sdk-ui-gen-ai/package.json
  libs/sdk-ui-geo/package.json
  libs/sdk-ui-kit/package.json
  libs/sdk-ui-pivot/package.json
  libs/sdk-ui-semantic-search/package.json
  libs/sdk-ui-tests/package.json
  libs/sdk-ui-theme-provider/package.json
  libs/sdk-ui-vis-commons/package.json
  libs/sdk-ui/package.json
  skel/sdk-skel-tsx/package.json
Labels: skip publish

#6693 docs: explicitly specify supported React versions
  docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
Labels: skip publish

#6715 fix: remove skip test
  libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts
Labels: skip publish
