Repository gooddata/gooddata-ui-sdk, pull requests merged in 2025-04, with the labels that each got.

#6162 Merge release into master
  NOTICE
  common/changes/@gooddata/sdk-ui-all/IMJ-STL-1080_2025-03-20-10-06.json
  common/changes/@gooddata/sdk-ui-all/ovel-fix-date-filter-reset-on-cancel_2025-04-03-08-12.json
  common/changes/@gooddata/sdk-ui-all/ovel-fix-search-w-apply-crash_2025-03-31-10-21.json
  common/changes/@gooddata/sdk-ui-all/pb-critical-optimize-out-all_2025-03-05-15-08.json
  docs/config/public/params.toml
  docs/layouts/index.redir
  libs/sdk-ui-all/CHANGELOG.json
  libs/sdk-ui-all/CHANGELOG.md
Labels: skip publish

#6175 chore: fix e2e PR commands
  .github/workflows/pull-request-comment.yaml
Labels: skip publish

#6176 chore: change backend for isolated records
  libs/sdk-ui-tests-e2e/.env.template
  libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
Labels: skip publish

#6180 fix: execution cancelling in pivot table
  libs/sdk-ui-pivot/src/CorePivotTable.tsx
Labels: ready to review

#6232 Schedule automation filters
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/automations/index.ts
  libs/sdk-model/src/execution/filter/index.ts
  libs/sdk-model/src/index.ts
  libs/sdk-ui-dashboard/.dependency-cruiser.cjs
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/_staging/dashboard/dashboardFilterConverter.ts
  libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts
  libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
  libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
  libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
  libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationDashboardFilters.ts
  libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts
  libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
  libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts
  libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
  libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
  libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/types.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultLoadingScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/DashboardAttachments.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/WidgetAttachments.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
  libs/sdk-ui-dashboard/styles/scss/automationFilters.scss
  libs/sdk-ui-dashboard/styles/scss/main.scss
  libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
Labels: do not merge

#6242 Merge release into master
  NOTICE
  common/changes/@gooddata/sdk-ui-all/ine-lx-976-4_2025-04-14-13-34.json
  common/changes/@gooddata/sdk-ui-all/ine-lx-976_2025-04-07-14-37.json
  docs/config/public/params.toml
  docs/layouts/index.redir
  libs/sdk-ui-all/CHANGELOG.json
  libs/sdk-ui-all/CHANGELOG.md
Labels: skip publish

#6255 fix: dashboard overrideDefaultFilters
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
  libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts
  libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
  libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextState.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
Labels: ready to review

#6269 fix: automation attribute filters reloading
  libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
  libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilterContext.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
Labels: ready to review

#6273 Merge rel/10.25 into master
  libs/sdk-ui-all/CHANGELOG.json
  libs/sdk-ui-all/CHANGELOG.md
  libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx
Labels: skip publish

#6281 fix: cancel token propagation
  libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
Labels: ready to review
