Repository gooddata/gooddata-ui-sdk, pull requests merged in 2025-02, with the labels that each got.

#5885 fix: dashboard load optimizations
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
  libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
  libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
Labels: ready to review

#5891 Merge release into master
  docs/config/public/params.toml
  docs/layouts/index.redir
  libs/sdk-ui-all/CHANGELOG.json
  libs/sdk-ui-all/CHANGELOG.md
Labels: skip publish

#5912 feat: reorder palette calls
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
Labels: do not merge

#5942 feat: add enableExecutionCancelling feature flag
  libs/sdk-backend-tiger/src/backend/features/feature.ts
  libs/sdk-backend-tiger/src/backend/uiFeatures.ts
  libs/sdk-model/api/sdk-model.api.md
  libs/sdk-model/src/settings/index.ts
Labels: ready to review

#5943 feat: add core support for execution cancelling
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/customBackend/execution.ts
  libs/sdk-backend-base/src/decoratedBackend/execution.ts
  libs/sdk-backend-base/src/dummyBackend/index.ts
  libs/sdk-backend-base/src/normalizingBackend/index.ts
  libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
  libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/execution/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
  libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/AbstractProvider.test.ts.snap
  libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/ComparisonProvider.test.ts.snap
Labels: ready to review

#5964 feat: execution cancelling in charts
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/cachingBackend/index.ts
  libs/sdk-backend-base/src/decoratedBackend/execution.ts
  libs/sdk-backend-base/src/eventingBackend/index.ts
  libs/sdk-backend-base/src/normalizingBackend/index.ts
  libs/sdk-backend-base/src/toolkit/execution.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/backend/index.ts
  libs/sdk-backend-spi/src/errors/index.ts
  libs/sdk-backend-spi/src/index.ts
  libs/sdk-backend-spi/src/workspace/execution/index.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/executionFactory.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
  libs/sdk-backend-tiger/src/cancelation/index.ts
  libs/sdk-backend-tiger/src/utils/errorHandling.ts
  libs/sdk-ui-charts/api/sdk-ui-charts.api.md
  libs/sdk-ui-charts/src/charts/_commons/chartDefinition.ts
  libs/sdk-ui-charts/src/charts/headline/Headline.tsx
  libs/sdk-ui-charts/src/charts/xirr/Xirr.tsx
  libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
  libs/sdk-ui-charts/src/interfaces/chartConfig.ts
  libs/sdk-ui-charts/src/interfaces/chartProps.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
  libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx
  libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
  libs/sdk-ui-geo/api/sdk-ui-geo.api.md
  libs/sdk-ui-geo/src/GeoChart.ts
  libs/sdk-ui-geo/src/GeoPushpinChart.tsx
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/areaChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/barChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bubbleChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bulletChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/columnChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/comboChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/dependencyWheelChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/donutChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/funnelChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/headline.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/heatmap.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/lineChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/pieChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/sankeyChart.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/scatterPlot.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/treemap.test.tsx.snap
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/xirr.test.tsx.snap
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx
  libs/sdk-ui/src/base/vis/VisualizationProps.ts
Labels: ready to review

#5557 feat: handle export raw data
  libs/api-client-tiger/src/execution.ts
  libs/sdk-backend-base/api/sdk-backend-base.api.md
  libs/sdk-backend-base/src/decoratedBackend/execution.ts
  libs/sdk-backend-base/src/normalizingBackend/index.ts
  libs/sdk-backend-spi/api/sdk-backend-spi.api.md
  libs/sdk-backend-spi/src/workspace/execution/index.ts
  libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
  libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/_staging/errors/errorPredicates.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/index.ts
  libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts
  libs/sdk-ui-dashboard/src/model/commands/base.ts
  libs/sdk-ui-dashboard/src/model/commands/index.ts
  libs/sdk-ui-dashboard/src/model/commands/insight.ts
  libs/sdk-ui-dashboard/src/model/store/executionResults/executionResultsSelectors.ts
  libs/sdk-ui-dashboard/src/model/store/index.ts
  libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
  libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
  libs/sdk-ui-dashboard/src/presentation/widget/common/useRawExportHandler.ts
  libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillModalFooter.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillModalRawExportOptions.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
  libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
  libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/index.tsx
  libs/sdk-ui/src/base/vis/export.ts
Labels: ready to review

#5968 feat: cancel executions in PivotTable/Repeater
  libs/sdk-backend-base/src/cachingBackend/index.ts
  libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx
  libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx
  libs/sdk-ui-dashboard/src/presentation/scheduledEmail/utils/tests/utils.test.ts
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap
  libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
  libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md
  libs/sdk-ui-pivot/src/CorePivotTable.tsx
  libs/sdk-ui-pivot/src/impl/data/dataSource.ts
  libs/sdk-ui-pivot/src/impl/tableFacade.ts
  libs/sdk-ui-pivot/src/impl/tableFacadeInitializer.ts
  libs/sdk-ui-pivot/src/publicTypes.ts
  libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/repeater.test.tsx.snap
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/base/react/CancelablePromise.ts
  libs/sdk-ui/src/base/react/PromiseCache.ts
  libs/sdk-ui/src/base/react/tests/CancelablePromise.test.ts
  libs/sdk-ui/src/base/react/useCancelablePromise.ts
  libs/sdk-ui/src/execution/withExecutionLoading.tsx
Labels: ready to review

#5972 feat: execution cancelling in public API
  common/changes/@gooddata/sdk-ui-all/mkn-f1-1112_2025-02-25-09-21.json
  libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
  libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts
  libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts
  libs/sdk-ui/api/sdk-ui.api.md
  libs/sdk-ui/src/execution/DataViewLoader.tsx
  libs/sdk-ui/src/execution/Execute.tsx
  libs/sdk-ui/src/execution/ExecuteInsight.tsx
  libs/sdk-ui/src/execution/RawExecute.tsx
  libs/sdk-ui/src/execution/useExecutionDataView.ts
  libs/sdk-ui/src/execution/useInsightDataView.ts
  libs/sdk-ui/src/execution/withExecution.ts
  libs/sdk-ui/src/execution/withExecutionLoading.tsx
Labels: ready to review

#5973 fix: use proper selector function
  libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts
  libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts
Labels: ready to review

#5987 fix: enhance telemetry capabilities
  libs/sdk-ui/src/base/react/CorrelationContext.tsx
Labels: ready to review
